### PR TITLE
Add experimental table converter

### PR DESCRIPTION
**Pull request by Sparrow0hawk**
This is a draft PR that merges in the changes from the RSE project work branch. The process for accepting and merging this PR is documented in #14 

It introduces:
- dependency on [`nutrientprofiler`](https://github.com/Leeds-CDRC/nutrientprofiler) changes to base Dockerfile
- Adds an R directory containing R script Shiny components for UI and server side of the Table converter
- Also adds a section for most of the actual server logic to the bottom of `server.R`

### CODE REVIEW

**Comment by Sparrow0hawk** [comment]
Unsure of why tests are running here but am not concerned about failures. The actions here are just to push changes to the test deployment and have no bearing on the main deployment.

**Comment by Sparrow0hawk** [comment]
Hi @murphyqm, do you want me to close this PR so you can open up your own PR from the same branch?

**Comment by Sparrow0hawk** [comment]
> Hi @murphyqm, do you want me to close this PR so you can open up your own PR from the same branch?

Just checking if you've seen this @murphyqm ?

**Comment by murphyqm** [comment]
Closing this off now @Sparrow0hawk to save you from notification spam!

Will reopen a new PR once we are ready to launch v2.

**Pull request closed without merging**
